// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBdIgtuFCp5Kl-SSYnutbcX6ND3Tv3nc8',
    appId: '1:151313069336:web:8e7b7323c85594775d9a6d',
    messagingSenderId: '151313069336',
    projectId: 'e-commerce-98666',
    authDomain: 'e-commerce-98666.firebaseapp.com',
    storageBucket: 'e-commerce-98666.appspot.com',
    measurementId: 'G-K7NXPS2HDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_UNJt3bSOSfnT0HccFFjs3O1UUz-jWE',
    appId: '1:151313069336:android:0c3dd424e25c6c625d9a6d',
    messagingSenderId: '151313069336',
    projectId: 'e-commerce-98666',
    storageBucket: 'e-commerce-98666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3EjQEFxID3sDpxPZun-vFVzIVwoWtcRI',
    appId: '1:151313069336:ios:856f82816112c2d85d9a6d',
    messagingSenderId: '151313069336',
    projectId: 'e-commerce-98666',
    storageBucket: 'e-commerce-98666.appspot.com',
    iosClientId: '151313069336-npjve2jq2ft1spm6l4ha7ld8rhjnlnqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
